title: JLAMP17 - Habanero Phaser formalization
baseurl: /jlamp17
email: cogumbreiro@rice.edu

highlighter: rouge

markdown: kramdown


kramdown:
  input: GFM
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
    
#sass:
# style: compressed

exclude:
- README.md

# gems: [jekyll-paginate]
