title: JLAMP17 - Habanero Phaser formalization
baseurl: /jlamp17
email: cogumbreiro@rice.edu

highlighter: rouge

markdown: kramdown


kramdown:
  input: GFM
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
    
#sass:
# style: compressed

exclude:
- README.md

# gems: [jekyll-paginate]
