title: JLAMP17 - Habanero Phaser formalization
baseurl: /jlamp17
email: cogumbreiro@rice.edu

highlighter: rouge
# markdown: kramdown

#sass:
# style: compressed

exclude:
- README.md

# gems: [jekyll-paginate]
